# Generated by Django 4.2.7 on 2023-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addroom_modelTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('no_of_beds', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'addrooms',
            },
        ),
    ]
