# Generated by Django 4.2.7 on 2023-12-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_addroom_modeltable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom_modeltable',
            name='status',
            field=models.CharField(default='available', max_length=50, null=True),
        ),
    ]
